name: Merge upstream branches
on: [push]
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'nadeemyaseen-lm'
          git config --global user.email 'nadeemyaseen-lm@users.noreply.github.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git checkout -b from_upstream
          git pull --no-edit origin from_upstream 2>/dev/null
          git remote add upstream https://github.com/mahmoodulhassan-rs/repo_upstream.git
          git fetch upstream

          git merge --no-edit upstream/master
          git push --set-upstream origin from_upstream
          git checkout master
  auto-pull-request:
    needs: merge
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "from_upstream"
          PULL_REQUEST_BRANCH: "master"
